### ISSUE TITLE
ფონტის რევიუს გვერდზე ტექსტის შეცვლა

### ISSUE THREAD

**Issue by thecotne** [web-fonts/web-fonts.github.io#1]
ვარიანტები

```
ჩიტს გაჰქონდა ჟღურტული ზეცაში, კვართიან საპყარს ძილს უფრთხობს ჭიქის ჯახუნი

აბგად ევზათ იკალმანო, პაჟა რასტა უფქა ღაყაშ, ჩაცა ძაწა ჭან ხან ჯან ჰაე

აბგად ევზეთ იკალ მანო, პაჟა რასტა უფქა ღაყაშ, ჩაცა ძაწა ჭახა ჯაჰო

ჭოპორტელმა ყარაჩოღელმა ვაჟიკამ ძუნწ და ცოფიან ათაბაგს ქაჯი შეხერეზადა წაჰგვარა
```

 წყარო https://forum.ge/?f=39&showtopic=33770686&st=15

**Comment by thecotne** [comment]
@Landish

**Comment by liorocks** [comment]
მქონდა მაგის იდეა, ადრე ვიკითხე კიდეც გრუპაში, და აქედან 2 ვარიანტი ვცადე ადრე და სიმართლე რომ გითხრა, ვიზუალურად, რატომღაც ანბანი უფრო მომეწონა პირადად მე ვიდრე ეს რთულად წასაკითხი ტექსტები, როგორც მომხმარებელს გამიჭირდა თითოეული ასოს აღქმა.

ამ ეტაპზე არ მინდა პირდაპირ ჩავსვა რომელიმე, ჯერ გრუპაშიც ვიკითხოთ, სხვების აზრი და ვნახოთ, ხმათა უმრავლესობით რა და როგორ გადაწყდება და მერე ამის შეცვლა არ წამოადგენს პრობლემას : )

**Comment by xxzefgh** [comment]
Default იყოს ანბანი და გვერდით დროფდაუნი სხვა ტექსტებით
