### ISSUE TITLE
ყველა ფონტის გადმოწერის შესაძლებლობა (დიზაინერებისთვის)

### ISSUE THREAD

**Issue by thecotne** [web-fonts/web-fonts.github.io#3]
დიზაინერს ვანახე ეს საიტი ამ ფონტების გამოყენება მარტივად შეგვიძლია მეთქი და ყველა როგორ გადმოვწეროო და გავჭედე :D 

კარგი იქნება ყველა ფონტის ttf ვერსია რომ იყოს სადმე zip

**Comment by liorocks** [comment]
როგორც ასეთი ttf-ების გადმოწერა თემატიკიდან ამოვარდნილად მიმაჩნია. 
ეგ ფუნქციონალი fonts.ge-ს უფრო შეესაბამება.
მარა, ნუ "ყველა პაკეტის" გადმოწერის დამატება შეიძლება, თუმცა ამაზე დროის დაკარგვა არ მინდა, ასე რომ pull's are welcome.

**Comment by thecotne** [comment]
``` bash
git clone https://github.com/web-fonts/cdn.git
mkdir webfonts
mv cdn/fonts/**/*.ttf webfonts
zip -r webfonts.zip webfonts

rm -rf cdn
rm -rf webfonts
```

ამ სკრიპტით შევქმენი zip და მომავალში შეიძლება ამის ci ში გადატანა და github ის რელიზებზე მიბმა
კაი პონტია ყველა ფონტის ერთად დაყენება psd ებში რო მარტივად ჩასვა ფონტი და ...

**Comment by liorocks** [comment]
@thecotne აგერ რეპო ვქენი და თუ დაპუშავ, კაი იქნება : ) 

https://github.com/web-fonts/ttf

**Comment by thecotne** [comment]
@Landish ვერ დავფუშავ მანდ უფლება არ მაქ და ვერც დავფორკავ კომიტები რახან არ აქვს არ იფორკება

**Comment by liorocks** [comment]
ანუ, დაფულე და მე დავმერჯავ :D

**Comment by thecotne** [comment]
ხოდა მაგას ვამბობ არ იფორკება და ავერც დავპულავ :D

**Comment by liorocks** [comment]
try now

**Comment by thecotne** [comment]
ამ რეპოს download zip სადმე საიტზე რო გავლინკოთ მთლად კაი იქნება

**Comment by liorocks** [comment]
<img width="582" alt="screen shot 2016-01-31 at 8 11 53 pm" src="https://cloud.githubusercontent.com/assets/534610/12703202/e8c5f442-c856-11e5-9e0c-9f39380d3323.png">

ამაზე რას იტყვი?

**Comment by thecotne** [comment]
წავა მარა კონტექსტიდან ამოგლეჯილია 
დანარჩენი ღილაკები მაგ ზოლში ფილტრაციას აკეთებს და ეგ ვაფშე სხვა ტიპია

**Comment by liorocks** [comment]
ვიცი, მარა უკეთესი ამ წუთას ვერ მოვიფიქრე :D

**Comment by thecotne** [comment]
footer ში რო დასვა cdn ის მერე?

**Comment by liorocks** [comment]
that was my 2nd thought ...

**Comment by liorocks** [comment]
done
