### ISSUE TITLE
bpg arial caps

### ISSUE THREAD

**Issue by thecotne** [web-fonts/web-fonts.github.io#4]
https://bpgfonts.wordpress.com/2009/02/27/bpg-arial/
ამ ლინკზე არის bpg arial და bpg arial caps და web-fonts.ge ზე არაა caps ი

@Landish

**Comment by liorocks** [comment]
Package-იც არ მაქვს. გავაკეთებ ამ დღეებში :  )

**Comment by thecotne** [comment]
@Landish still waiting

**Comment by liorocks** [comment]
<img width="220" alt="screen shot 2016-02-24 at 6 25 37 pm" src="https://cloud.githubusercontent.com/assets/534610/13288137/07160862-db24-11e5-935c-e4141cb56246.png">

**Comment by liorocks** [comment]
http://www.font2web.com/-მა წაიღო.

Enjoy: https://web-fonts.ge/bpg-arial-caps/

**Comment by thecotne** [comment]
thx
