### ISSUE TITLE
DJVM font

### ISSUE THREAD

**Issue by xxzefgh** [web-fonts/web-fonts.github.io#5]
ეს რა ფონტია? on.ge-ზე იყენებენ

```
@font-face {
    font-family: "DJVM";
    src: url(//static.on.ge/global/assets/fonts/DejaVuSansM.eot);
    src: url(//static.on.ge/global/assets/fonts/DejaVuSansM.eot?#iefix) format("embedded-opentype"),url(//static.on.ge/global/assets/fonts/DejaVuSansM.woff) format("woff"),url(//static.on.ge/global/assets/fonts/DejaVuSansM.ttf) format("truetype"),url(//static.on.ge/global/assets/fonts/DejaVuSansM.svg) format("svg");
}
```

**Comment by liorocks** [comment]
როგორც ჩანს, Dejavu Sans Mono Book არის 

<img width="513" alt="screen shot 2016-11-22 at 7 44 57 pm" src="https://cloud.githubusercontent.com/assets/534610/20530315/6f414944-b0ec-11e6-9da5-3010720fc3d9.png">

ამ ფონტის გადმოწერა და preview შეგიძლია აქ https://www.fontsquirrel.com/fonts/dejavu-sans-mono
